### ISSUE TITLE
Running Tutorial

### ISSUE THREAD

**Issue by steflbert** [MStarmans91/WORC#34]
After hearing the ECR talk, I wanted to try out WORC and tried to run the tutorial. The problem is, if I try to execute the experiment (without any changes) I get the following error (from file C:\Users\USERNAME\AppData\Local\Temp\GS\W4AMFZHJ1L\tmp\fitandscore\id_0__0__0\__fastr_result__.yaml)

I used pip to install WORC, because I couldn't find the package using conda.

Traceback (most recent call last):
  File "c:\users\sa37\phd\code\radiomics\worc\venv\lib\site-packages\WORC\resources\fastr_tools\worc\bin\fitandscore_tool.py", line 84, in <module>
    main()
  File "c:\users\sa37\phd\code\radiomics\worc\venv\lib\site-packages\WORC\resources\fastr_tools\worc\bin\fitandscore_tool.py", line 58, in main
    ret = Parallel(
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\joblib\parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\fitandscore.py", line 243, in fit_and_score
    imputer.fit(feature_values)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\featureprocessing\Imputer.py", line 81, in fit
    self.Imputer.fit(X, y)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\missingpy\knnimpute.py", line 231, in fit
    raise ValueError("There are only %d samples, but n_neighbors=%d."
ValueError: There are only 8 samples, but n_neighbors=9.

And the experiment fails. Do you have any idea what could cause this problem? I tried it in the debugger, there are a few sample beforehand, where it does work.

**Comment by MStarmans91** [comment]
Hi @steflbert , thanks for trying out WORC! This bug should not occur in the tutorial, as this is run as the unit test, but nevertheless it did. The issue suggests that WORC tries to use imputation for missing feature values with a K-nearest neighbor (KNN) algorithm, using 9 neighbors, while there are only 8 samples in the training dataset. Whether the use of 9 neighbors is suitable of course depends on your dataset, but on a small dataset, such as the tutorial, it makes no sense to use such a high number or even an KNN algorithm at all.

I will make sure to change the settings in the defaults in the next version. For now, can you manually make sure that the KNN algorithm is not used by just before the `experiment.execute()` line, adding the following:

`experiment.add_config_overrides({'Imputation': {'strategy': 'mean, median, most_frequent, constant'}})`

This will override the default in the config in which knn is used as imputation method. Please let me know if that fixed the issue.

**Comment by steflbert** [comment]
Thanks a lot for your help. The previous error disappeared now but I am getting a new one, which also seems to be related to cross-validation


with open(r'C:\Users\sa37\PhD\Code\Radiomics\WORC\WORCTutorial\WORC_Example_STWStrategyHN\classify\all\__fastr_result__.yaml') as file:...
Traceback (most recent call last):
  File "c:\users\sa37\phd\code\radiomics\worc\venv\lib\site-packages\WORC\resources\fastr_tools\worc\bin\TrainClassifier.py", line 64, in <module>
    main()
  File "c:\users\sa37\phd\code\radiomics\worc\venv\lib\site-packages\WORC\resources\fastr_tools\worc\bin\TrainClassifier.py", line 53, in main
    trainclassifier(feat_train=args.feat_train,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\trainclassifier.py", line 228, in trainclassifier
    trained_classifier = cv.crossval(config, label_data_train,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\crossval.py", line 325, in crossval
    trained_classifier = random_search_parameters(features=X_train,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\parameter_optimization.py", line 88, in random_search_parameters
    random_search.fit(features, labels)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\SearchCV.py", line 1743, in fit
    return self._fit(X, y, groups, sampled_params)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\SearchCV.py", line 1487, in _fit
    self.process_fit(n_splits=n_splits,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\SearchCV.py", line 755, in process_fit
    self.refit_and_score(X, y, best_parameters_all, best_parameters_est,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\SearchCV.py", line 812, in refit_and_score
    out = fit_and_score(X_fit, y, self.scoring,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\fitandscore.py", line 740, in fit_and_score
    raise e
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\WORC\classification\fitandscore.py", line 722, in fit_and_score
    ret = _fit_and_score(estimator, feature_values, y,
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 508, in _fit_and_score
    X_train, y_train = _safe_split(estimator, X, y, train)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\sklearn\utils\metaestimators.py", line 201, in _safe_split
    X_subset = _safe_indexing(X, indices)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\sklearn\utils\__init__.py", line 388, in _safe_indexing
    indices_dtype = _determine_key_type(indices)
  File "c:\Users\sa37\PhD\Code\Radiomics\WORC\venv\lib\site-packages\sklearn\utils\__init__.py", line 286, in _determine_key_type
    raise ValueError(err_msg)
ValueError: No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed

**Comment by MStarmans91** [comment]
Thank you for trying the fix. This seems an issue with scikit-learn / sklearn: which version of scikit-learn are you using? And which version of WORC? Maybe you can just send a `pip freeze` of your virtual environment. 

Currently, WORC requires sklearn verson 0.20.3, see the requirements.

**Comment by steflbert** [comment]
I had the wrong version of scikit-learninstalled (version 0.22) becasue the previous version did not work with python 3.8 so I installed python 3.6, which does work with scikit-learn0.20.3. The problem with that was that pickle protocol 5 is needed to read the hdf5 files. So what ended up working was using python 3.8 with scikit-learn version 0.21.1
[installed.txt](https://github.com/MStarmans91/WORC/files/4980948/installed.txt)

Which python version are you using?

**Comment by MStarmans91** [comment]
I am using Python 3.7, 3.7.4 to be exact. I just ran an experiment in a clean Python 3.7.4 environment on Windows, which does work. So my guess is that indeed your version of scikit-learn and possibly also Python is raising an issue. If you are using anaconda, you can easily create a virtual environment with a different version: `conda create --name YourName python=3.7.4`. I would suggest to do so. Meanwhile, I will check whether supporting Python 3.8 would be possible besides the merge to the new sklearn. FYI: I've also tested WORC with Python 3.6.8, so I guess most 3.6 versions would work as well if you prefer that.

**Comment by steflbert** [comment]
I did a clean install in Anaconda (with pip, I did not find a cuda package) and the processing does work. Maybe the problem was a leftover file from the previous computation. It should not be possible to create a pickle file with a higher protocol version than the current python version can read. So thank you for all your help.

**Comment by steflbert** [comment]
The only thing I had to change was the vfs.py file in fastr/core, otherwise I have issues with the windows path because of the case insesitivity in windows.
