### ISSUE TITLE
Problems to install worc

### ISSUE THREAD

**Issue by josemanuel097** [MStarmans91/WORC#4]
Trying to install WORC i get the following message:

    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/jtovar/worc_prostate/worc_pros/build/cryptography/setup.py", line 28, in <module>
        "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/jtovar/worc_prostate/worc_pros/build/cryptography/setup.py", line 28, in <module>

    "cryptography requires setuptools 18.5 or newer, please upgrade to a "

RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools

**Comment by MStarmans91** [comment]
Seems like you run a rather old version of setuptools need to upgrade setuptools manually first. Which version of Python are you using? Might be that the default setuptools in there is too old. Can you try manually upgrading setuptools first?

**Comment by josemanuel097** [comment]
Yeah , I was using an older version. The update fixed this problem
